# -*- make -*-
BASE=..
SUBDIR=doc

# Bring in the default rules
include ../buildlib/defaults.mak

# Examples
SOURCE = examples/config.py examples/configisc.py examples/tagfile.py \
         examples/versiontest.py examples/checkstate.py \
	 examples/recommends.py
TO = $(DOC)
include $(COPY_H)
